---
# tasks file for roles/app
- name: Run Backend App
  docker_container:
    name: backend
    image: schrk06/tp-devops-simple-api:latest
    networks:
      - name: app-network
    restart_policy: always
    env:
      DB_URL: "jdbc:postgresql://database:5432/db"
      DB_USERNAME: "usr"
      DB_PASSWORD: "pwd"