---
# tasks file for roles/app
- name: Run Backend App
  docker_container:
    name: simple-api # Le nom de ton backend sur le réseau
    image: schrk06/tp-devops-simple-api:latest # L'image de ton API !
    networks:
      - name: app-network
    restart_policy: always