---
# tasks file for roles/proxy
- name: Run HTTPD Proxy
  docker_container:
    name: httpd-proxy
    image: schrk06/tp-devops-httpd:latest
    pull: true
    networks:
      - name: app-network
    restart_policy: always
    ports:
      - "80:80"